theme: jekyll-theme-leap-day
title: Tips for your Daily Handoff
description: Helping you and your team ease your way into Follow-the-sun development
google_analytics: UA-140665192-1
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
